// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIl4IoQxOWxQQuDa-oAZyJFyjyndQ80Qo',
    appId: '1:7797927713:web:da03dca5898151f5651860',
    messagingSenderId: '7797927713',
    projectId: 'firebase-implementation',
    authDomain: 'fir-implementation-a9b13.firebaseapp.com',
    storageBucket: 'firebase-implementation.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAzgJl5ZMMsqJIv3jlcnl41iv-AtUrv3c',
    appId: '1:7797927713:android:7bb60dc7f6547e90651860',
    messagingSenderId: '7797927713',
    projectId: 'firebase-implementation',
    storageBucket: 'firebase-implementation.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUa0ZOcjz5BxTGGd03-7FbpMZMnO8ER7M',
    appId: '1:7797927713:ios:d40d3854e288d9cf651860',
    messagingSenderId: '7797927713',
    projectId: 'firebase-implementation',
    storageBucket: 'firebase-implementation.firebasestorage.app',
    iosBundleId: 'com.example.firebaseImplementation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUa0ZOcjz5BxTGGd03-7FbpMZMnO8ER7M',
    appId: '1:7797927713:ios:d40d3854e288d9cf651860',
    messagingSenderId: '7797927713',
    projectId: 'firebase-implementation',
    storageBucket: 'firebase-implementation.firebasestorage.app',
    iosBundleId: 'com.example.firebaseImplementation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIl4IoQxOWxQQuDa-oAZyJFyjyndQ80Qo',
    appId: '1:7797927713:web:caa4967d27fd9245651860',
    messagingSenderId: '7797927713',
    projectId: 'firebase-implementation',
    authDomain: 'fir-implementation-a9b13.firebaseapp.com',
    storageBucket: 'firebase-implementation.firebasestorage.app',
  );
}
